export default {
  AQUEDUX_CLIENT_DEFINE_CHANNEL: 'AQUEDUX_CLIENT_DEFINE_CHANNEL',
  AQUEDUX_CLIENT_JOIN_CHANNEL: 'AQUEDUX_CLIENT_JOIN_CHANNEL',
  AQUEDUX_CLIENT_LEAVE_CHANNEL: 'AQUEDUX_CLIENT_LEAVE_CHANNEL',
  AQUEDUX_PING: 'AQUEDUX_PING',
  AQUEDUX_PING_SENT: 'AQUEDUX_PING_SENT',
  AQUEDUX_PING_RESTART: 'AQUEDUX_PING_RESTART',
  AQUEDUX_PING_KO: 'AQUEDUX_PING_KO'
}
