export default {
  AQUEDUX_CLIENT_CHANNEL_DEFINE: 'AQUEDUX_CLIENT_CHANNEL_DEFINE',
  AQUEDUX_CLIENT_CHANNEL_JOIN: 'AQUEDUX_CLIENT_CHANNEL_JOIN',
  AQUEDUX_CLIENT_CHANNEL_LEAVE: 'AQUEDUX_CLIENT_CHANNEL_LEAVE',
  AQUEDUX_CLIENT_MESSAGE_RECEIVED: 'AQUEDUX_CLIENT_MESSAGE_RECEIVED',
  AQUEDUX_CLIENT_PING: 'AQUEDUX_CLIENT_PING',
  AQUEDUX_PING_SENT: 'AQUEDUX_PING_SENT',
  AQUEDUX_PING_RESTART: 'AQUEDUX_PING_RESTART',
  AQUEDUX_PING_KO: 'AQUEDUX_PING_KO'
}
