export default {
  AQUEDUX_CLIENT_CHANNEL_JOIN: 'AQUEDUX_CLIENT_CHANNEL_JOIN',
  AQUEDUX_CLIENT_CHANNEL_LEAVE: 'AQUEDUX_CLIENT_CHANNEL_LEAVE',
  AQUEDUX_CLIENT_MESSAGE_RECEIVED: 'AQUEDUX_CLIENT_MESSAGE_RECEIVED',
  AQUEDUX_CHANNEL_SNAPSHOT: 'AQUEDUX_CHANNEL_SNAPSHOT',
  AQUEDUX_CLIENT_START: '@aquedux/start',
  AQUEDUX_CLIENT_STOP: '@aquedux/stop'
}
